export const GET_EVENTS_START = 'GET_EVENTS_START';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const GET_SINGLE_EVENT_START = 'GET_SINGLE_EVENT_START';
export const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS';
export const GET_SINGLE_EVENT_ERROR = 'GET_SINGLE_EVENT_ERROR';

export const ADD_EVENT_START = 'ADD_EVENT_START';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_ERROR = 'ADD_EVENT_ERROR';

export const EDIT_EVENT_START = 'EDIT_EVENT_START';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR';

export const DELETE_EVENT_START = 'DELETE_EVENT_START';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

// action.js types

export const SET_NAME = 'SET_NAME';
export const SET_USERNAME = 'SET_USERNAME';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const EDIT_USER_START = 'EDIT_USER_START';
export const EDIT_USER_START_PROCESSING = 'EDIT_USER_START_PROCESSING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';
export const EDIT_USER_CANCEL = 'EDIT_USER_CANCEL';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const SEARCH_FOR_TRACK_START = 'SEARCH_FOR_TRACK_START';
export const SEARCH_FOR_TRACK_SUCCESS = 'SEARCH_FOR_TRACK_SUCCESS';
export const SEARCH_FOR_TRACK_ERROR = 'SEARCH_FOR_TRACK_ERROR';

export const GET_DJ_START = 'GET_DJ_START';
export const GET_DJ_SUCCESS = 'GET_DJ_SUCCESS';
export const GET_DJ_ERROR = 'GET_DJ_ERROR';

// export const ADD_SONG_TO_PLAYLIST_START = 'ADD_SONG_TO_PLAYLIST_START';
// export const ADD_SONG_TO_PLAYLIST_SUCCESS = 'ADD_SONG_TO_PLAYLIST_SUCCESS';
// export const ADD_SONG_TO_PLAYLIST_ERROR = 'ADD_SONG_TO_PLAYLIST_ERROR';

// export const REMOVE_SONG_FROM_PLAYLIST_START =
//   'REMOVE_SONG_FROM_PLAYLIST_START';
// export const REMOVE_SONG_FROM_PLAYLIST_SUCCESS =
//   'REMOVE_SONG_FROM_PLAYLIST_SUCCESS';
// export const REMOVE_SONG_FROM_PLAYLIST_ERROR =
//   'REMOVE_SONG_FROM_PLAYLIST_ERROR';

// export const GET_PLAYLIST_START = 'GET_PLAYLIST_START';
// export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
// export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR';

// export const ADD_TO_SONG_REDUCER_START = 'ADD_TO_SONG_REDUCER_START';
// export const ADD_TO_SONG_REDUCER_SUCCESS = 'ADD_TO_SONG_REDUCER_SUCCESS';
// export const ADD_TO_SONG_REDUCER_ERROR = 'ADD_TO_SONG_REDUCER_ERROR';

// export const GET_SONG_BY_ID_START = 'GET_SONG_BY_ID_START';
// export const GET_SONG_BY_ID_SUCCESS = 'GET_SONG_BY_ID_SUCCESS';
// export const GET_SONG_BY_ID_ERROR = 'GET_SONG_BY_ID_ERROR';

// export const ADD_VOTE_START = 'ADD_VOTE_START';
// export const ADD_VOTE_SUCCESS = 'ADD_VOTE_SUCCESS';
// export const ADD_VOTE_ERROR = 'ADD_VOTE_ERROR';

// export const EDIT_QUEUE_NUM_START = 'EDIT_QUEUE_NUM_START';
// export const EDIT_QUEUE_NUM_SUCCESS = 'EDIT_QUEUE_NUM_SUCCESS';
// export const EDIT_QUEUE_NUM_ERROR = 'EDIT_QUEUE_NUM_ERROR';

// Search Actions

export const GET_SEARCH_RESULTS_START = 'GET_SEARCH_RESULTS_START';

export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_PREDICT_RESULTS_SUCCESS = 'GET_PREDICT_RESULTS_SUCCESS';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';
export const MOVE_TRACK_SUCCESS = 'MOVE_TRACK_SUCCESS';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const REMOVE_PLAYLIST_TRACK_SUCCESS = 'REMOVE_PLAYLIST_TRACK_SUCCESS';

export const GET_TRACK_LIST = 'GET_TRACK_LIST';
export const ADD_SEARCH_TRACK = 'ADD_SEARCH_TRACK';

export const GET_SEARCH_RESULTS_ERROR = 'GET_SEARCH_RESULTS_ERROR';
export const GET_TRACK_LIST_ERROR = 'GET_TRACK_LIST_ERROR';
export const GET_PREDICT_RESULTS_ERROR = 'GET_PREDICT_RESULTS_ERROR';

export const ADD_SEARCH_TRACK_ERROR = 'ADD_SEARCH_TRACK_ERROR';
export const DELETE_TRACK_ERROR = 'DELETE_TRACK_ERROR';
export const MOVE_TRACK_ERROR = 'MOVE_TRACK_ERROR';
export const GET_PLAYLISTS_ERROR = 'GET_TRACKLISTS_ERROR';
export const REMOVE_PLAYLIST_TRACK_ERRROR = 'REMOVE_PLAYLIST_TRACK_ERRROR';
